# programa
PROG=grafo_kruskal
PROG2=grafo_kruskal_v2

# compilador
CC=g++

# flags para o compilador
CFLAGS=-Wall -g

all:
	$(CC) $(CFLAGS) -o $(PROG) $(PROG).cpp
	$(CC) $(CFLAGS) -o $(PROG2) $(PROG2).cpp

clean:
	rm -rf *.o *~ $(PROG) $(PROG2)
